 # name of pipeline workflow

name: viresh job

# trigger point
on:
  push:
    branches: ["main"]           #["dryrun-aws"]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps: # what excatly you want to run in ubuntu machine
    # calling first github action to 
    - name: taking code from my repo
      uses: actions/checkout@v5
      with: 
        ref: main #dryrun-aws

    - name: hello world
      run: |
            echo "Hello World"
            git version
            whoami
            ls -a

# configure 
- name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-southeast-2          
- name: verify aws connection
  run: |
      echo "checking with command"
      aws s3 ls